name: 'Setup Environment'
description: 'Set up Python, Node.js and install dependencies'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22'
  install-deps:
    description: 'Install dependencies'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Set up Node.js
      uses: actions/setup-node@v5
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install dependencies
      if: ${{ inputs.install-deps == 'true' }}
      shell: bash
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -e .[dev]
        npm ci