version: '3.9'

services:
  web:
    build: .
    image: flask-tutorial:local
    container_name: flask-tutorial-web
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: flaskr
      FLASK_ENV: development
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:18-alpine
    container_name: flask-tutorial-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
