name: Deploy

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'release'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Build frontend assets
        run: make webpack

      - name: Generate SBOM with public versions
        uses: ./.github/actions/sbom
        with:
          generate-public: true
          upload-artifacts: true
          retention-days: 90

      - name: Upload Public SBOMs to Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            sbom/python-sbom-public.json
            sbom/javascript-sbom-public.json
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only
