name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      (github.event.workflow_run.conclusion == 'success' && 
       contains(github.event.workflow_run.head_commit.message, 'chore(master): release')) || 
      github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -e .[dev]
          npm ci

      - name: Build frontend assets
        run: make webpack

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only
