name: Release Please
on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: python
          include-v-in-tag: true
          extra-files: |
            package.json:$.version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
